name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "deploy/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "deploy/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - run: git tag ${{ steps.version.outputs.version }}
      - run: git push origin ${{ steps.version.outputs.version }}    

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PulsePlaylist.Standalone image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-standalone:${{ steps.version.outputs.version }} -f src/PulsePlaylist.ClientApp/Dockerfile .
            docker push ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-standalone:${{ steps.version.outputs.version }}    
      - name: Build and push PulsePlaylist.WebApp image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-webapp:${{ steps.version.outputs.version }} -f src/PulsePlaylist.WebApp/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-webapp:${{ steps.version.outputs.version }}

      - name: Build and push PulsePlaylist.Api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-api:${{ steps.version.outputs.version }} -f src/PulsePlaylist.Api/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/pulseplaylist-api:${{ steps.version.outputs.version }}

      - name: Update version in docker-compose file
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Updating docker-compose file with version ${{ steps.version.outputs.version }}"
          sed -i 's#blazordevlab/pulseplaylist-api:[0-9a-zA-Z\.\-]*#blazordevlab/pulseplaylist-api:${{ steps.version.outputs.version }}#' deploy/docker-compose.yml
          sed -i 's#blazordevlab/pulseplaylist-webapp:[0-9a-zA-Z\.\-]*#blazordevlab/pulseplaylist-webapp:${{ steps.version.outputs.version }}#' deploy/docker-compose.yml
          sed -i 's#blazordevlab/pulseplaylist-standalone:[0-9a-zA-Z\.\-]*#blazordevlab/pulseplaylist-standalone:${{ steps.version.outputs.version }}#' deploy/docker-compose.yml

      - name: Create Pull Request
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Docker Compose files to version ${{ steps.version.outputs.version }}"
          title: "Update Docker Compose to version ${{ steps.version.outputs.version }}"
          body: "Automatically updating Docker Compose version references to match the latest build version ${{ steps.version.outputs.version }}"
          branch: update-compose-version-${{ steps.version.outputs.version }}